from __future__ import annotations

from signal_noise.collector.base import CollectorMeta
from signal_noise.collector.yahoo_finance import _YahooCollector

YAHOO_TICKERS: list[tuple[str, str, str, str, str]] = [
    # (ticker, name, display, domain, category)
    ("^IXIC", "nasdaq", "NASDAQ Composite", "markets", "equity"),
    ("^DJI", "djia", "Dow Jones Industrial", "markets", "equity"),
    ("^RUT", "russell2000", "Russell 2000", "markets", "equity"),
    ("^STOXX50E", "eurostoxx50", "Euro Stoxx 50", "markets", "equity"),
    ("^FTSE", "ftse100", "FTSE 100", "markets", "equity"),
    ("^N225", "nikkei225", "Nikkei 225", "markets", "equity"),
    ("^HSI", "hang_seng", "Hang Seng Index", "markets", "equity"),
    ("^GDAXI", "dax", "DAX 40", "markets", "equity"),
    ("^FCHI", "cac40", "CAC 40", "markets", "equity"),
    ("^BSESN", "sensex", "BSE Sensex", "markets", "equity"),
    ("^KS11", "kospi", "KOSPI", "markets", "equity"),
    ("^TWII", "taiwan_weighted", "Taiwan Weighted", "markets", "equity"),
    ("^AXJO", "asx200", "ASX 200", "markets", "equity"),
    ("^VIX", "vix", "CBOE Volatility (VIX)", "markets", "equity"),
    ("^VVIX", "vvix", "VIX of VIX", "markets", "equity"),
    ("SI=F", "silver", "Silver Futures", "markets", "commodity"),
    ("CL=F", "oil_wti", "WTI Crude Oil", "markets", "commodity"),
    ("BZ=F", "oil_brent", "Brent Crude Oil", "markets", "commodity"),
    ("NG=F", "nat_gas", "Natural Gas Futures", "markets", "commodity"),
    ("HG=F", "copper", "Copper Futures", "markets", "commodity"),
    ("PL=F", "platinum", "Platinum Futures", "markets", "commodity"),
    ("PA=F", "palladium", "Palladium Futures", "markets", "commodity"),
    ("ZW=F", "wheat", "Wheat Futures", "markets", "commodity"),
    ("ZC=F", "corn", "Corn Futures", "markets", "commodity"),
    ("ZS=F", "soybean", "Soybean Futures", "markets", "commodity"),
    ("KC=F", "coffee", "Coffee Futures", "markets", "commodity"),
    ("CT=F", "cotton", "Cotton Futures", "markets", "commodity"),
    ("LBS=F", "lumber", "Lumber Futures", "markets", "commodity"),
    ("DX-Y.NYB", "dxy", "US Dollar Index (DXY)", "markets", "forex"),
    ("EURUSD=X", "eur_usd", "EUR/USD", "markets", "forex"),
    ("GBPUSD=X", "gbp_usd", "GBP/USD", "markets", "forex"),
    ("USDJPY=X", "usd_jpy", "USD/JPY", "markets", "forex"),
    ("AUDUSD=X", "aud_usd", "AUD/USD", "markets", "forex"),
    ("USDCHF=X", "usd_chf", "USD/CHF", "markets", "forex"),
    ("USDCAD=X", "usd_cad", "USD/CAD", "markets", "forex"),
    ("NZDUSD=X", "nzd_usd", "NZD/USD", "markets", "forex"),
    ("USDCNY=X", "usd_cny", "USD/CNY", "markets", "forex"),
    ("USDINR=X", "usd_inr", "USD/INR", "markets", "forex"),
    ("USDKRW=X", "usd_krw", "USD/KRW", "markets", "forex"),
    ("USDTRY=X", "usd_try", "USD/TRY", "markets", "forex"),
    ("USDBRL=X", "usd_brl", "USD/BRL", "markets", "forex"),
    ("^TNX", "us10y", "US 10Y Treasury Yield", "markets", "rates"),
    ("^TYX", "us30y", "US 30Y Treasury Yield", "markets", "rates"),
    ("^IRX", "us3m", "US 3M T-Bill Rate", "markets", "rates"),
    ("^FVX", "us5y", "US 5Y Treasury Yield", "markets", "rates"),
    ("XLF", "etf_financials", "Financial Select SPDR", "markets", "equity"),
    ("XLK", "etf_tech", "Technology Select SPDR", "markets", "equity"),
    ("XLE", "etf_energy", "Energy Select SPDR", "markets", "equity"),
    ("XLV", "etf_healthcare", "Health Care Select SPDR", "markets", "equity"),
    ("XLI", "etf_industrial", "Industrial Select SPDR", "markets", "equity"),
    ("XLP", "etf_staples", "Consumer Staples SPDR", "markets", "equity"),
    ("XLY", "etf_discretionary", "Consumer Discretionary SPDR", "markets", "equity"),
    ("XLB", "etf_materials", "Materials Select SPDR", "markets", "equity"),
    ("XLU", "etf_utilities", "Utilities Select SPDR", "markets", "equity"),
    ("XLRE", "etf_realestate", "Real Estate Select SPDR", "markets", "equity"),
    ("MSTR", "mstr", "MicroStrategy", "markets", "equity"),
    ("COIN", "coinbase", "Coinbase Global", "markets", "equity"),
    ("MARA", "mara", "Marathon Digital", "markets", "equity"),
    ("RIOT", "riot", "Riot Platforms", "markets", "equity"),
    # Consumer / fast food (Whopper inspiration)
    ("QSR", "qsr", "Restaurant Brands International", "sentiment", "attention"),
    ("MCD", "mcd", "McDonald's", "sentiment", "attention"),
    ("SBUX", "sbux", "Starbucks", "sentiment", "attention"),
    # S&P 500 top 50 by market cap (excl. already listed tickers)
    ("AAPL", "aapl", "Apple", "markets", "equity"),
    ("MSFT", "msft", "Microsoft", "markets", "equity"),
    ("NVDA", "nvda", "NVIDIA", "markets", "equity"),
    ("AMZN", "amzn", "Amazon", "markets", "equity"),
    ("GOOGL", "googl", "Alphabet (Google)", "markets", "equity"),
    ("META", "meta", "Meta Platforms", "markets", "equity"),
    ("BRK-B", "brk_b", "Berkshire Hathaway", "markets", "equity"),
    ("TSLA", "tsla", "Tesla", "markets", "equity"),
    ("AVGO", "avgo", "Broadcom", "markets", "equity"),
    ("JPM", "jpm", "JPMorgan Chase", "markets", "equity"),
    ("LLY", "lly", "Eli Lilly", "markets", "equity"),
    ("V", "visa", "Visa", "markets", "equity"),
    ("UNH", "unh", "UnitedHealth", "markets", "equity"),
    ("MA", "mastercard", "Mastercard", "markets", "equity"),
    ("XOM", "xom", "Exxon Mobil", "markets", "equity"),
    ("COST", "cost", "Costco", "markets", "equity"),
    ("HD", "hd", "Home Depot", "markets", "equity"),
    ("PG", "pg", "Procter & Gamble", "markets", "equity"),
    ("JNJ", "jnj", "Johnson & Johnson", "markets", "equity"),
    ("NFLX", "nflx", "Netflix", "markets", "equity"),
    ("ABBV", "abbv", "AbbVie", "markets", "equity"),
    ("CRM", "crm", "Salesforce", "markets", "equity"),
    ("BAC", "bac", "Bank of America", "markets", "equity"),
    ("ORCL", "orcl", "Oracle", "markets", "equity"),
    ("CVX", "cvx", "Chevron", "markets", "equity"),
    ("MRK", "mrk", "Merck", "markets", "equity"),
    ("KO", "ko", "Coca-Cola", "markets", "equity"),
    ("TMO", "tmo", "Thermo Fisher", "markets", "equity"),
    ("AMD", "amd", "AMD", "markets", "equity"),
    ("PEP", "pep", "PepsiCo", "markets", "equity"),
    ("ACN", "acn", "Accenture", "markets", "equity"),
    ("LIN", "lin", "Linde", "markets", "equity"),
    ("ADBE", "adbe", "Adobe", "markets", "equity"),
    ("WMT", "wmt", "Walmart", "markets", "equity"),
    ("CSCO", "csco", "Cisco", "markets", "equity"),
    ("ABT", "abt", "Abbott Labs", "markets", "equity"),
    ("NOW", "now_", "ServiceNow", "markets", "equity"),
    ("PM", "pm", "Philip Morris", "markets", "equity"),
    ("TXN", "txn", "Texas Instruments", "markets", "equity"),
    ("MS", "ms", "Morgan Stanley", "markets", "equity"),
    ("DIS", "dis", "Walt Disney", "markets", "equity"),
    ("DHR", "dhr", "Danaher", "markets", "equity"),
    ("NEE", "nee", "NextEra Energy", "markets", "equity"),
    ("QCOM", "qcom", "Qualcomm", "markets", "equity"),
    ("INTC", "intc", "Intel", "markets", "equity"),
    ("AMGN", "amgn", "Amgen", "markets", "equity"),
    # ── Real estate / REITs ──
    ("VNQ", "vnq", "Vanguard Real Estate ETF", "economy", "real_estate"),
    ("IYR", "iyr", "iShares US Real Estate ETF", "economy", "real_estate"),
    ("VNQI", "vnqi", "Vanguard Global ex-US Real Estate", "economy", "real_estate"),
    ("REET", "reet", "iShares Global REIT ETF", "economy", "real_estate"),
    ("XHB", "xhb", "SPDR Homebuilders ETF", "economy", "real_estate"),
    ("ITB", "itb", "iShares Home Construction ETF", "economy", "real_estate"),
    ("1343.T", "jreit", "NEXT FUNDS J-REIT ETF", "economy", "real_estate"),
    ("PLD", "pld", "Prologis (Logistics REIT)", "economy", "real_estate"),
    ("AMT", "amt", "American Tower REIT", "economy", "real_estate"),
    ("SPG", "spg", "Simon Property Group", "economy", "real_estate"),
    ("O", "realty_income", "Realty Income", "economy", "real_estate"),
    # ── Shipping / maritime ──
    ("BDRY", "bdry", "Breakwave Dry Bulk Shipping", "technology", "logistics"),
    ("BOAT", "boat", "SonicShares Global Shipping", "technology", "logistics"),
    ("SBLK", "sblk", "Star Bulk Carriers", "technology", "logistics"),
    ("ZIM", "zim", "ZIM Integrated Shipping", "technology", "logistics"),
    ("DAC", "dac", "Danaos Corporation", "technology", "logistics"),
    ("MATX", "matx", "Matson Inc", "technology", "logistics"),
    # ── Aviation ──
    ("JETS", "jets", "US Global Jets ETF", "technology", "aviation"),
    ("DAL", "dal", "Delta Air Lines", "technology", "aviation"),
    ("UAL", "ual", "United Airlines", "technology", "aviation"),
    ("LUV", "luv", "Southwest Airlines", "technology", "aviation"),
    ("AAL", "aal", "American Airlines", "technology", "aviation"),
    ("BA", "ba", "Boeing", "technology", "aviation"),
    ("AIR.PA", "airbus", "Airbus", "technology", "aviation"),
    # CBOE options indicators
    ("^SKEW", "cboe_skew", "CBOE SKEW Index", "markets", "equity"),
    # Agricultural commodities (gap fill)
    ("CC=F", "cocoa", "Cocoa Futures", "markets", "commodity"),
    ("LE=F", "live_cattle", "Live Cattle Futures", "markets", "commodity"),
    ("HE=F", "lean_hogs", "Lean Hogs Futures", "markets", "commodity"),
    ("ZR=F", "rough_rice", "Rough Rice Futures", "markets", "commodity"),
    ("OJ=F", "orange_juice", "Orange Juice Futures", "markets", "commodity"),
    # International / thematic ETFs
    ("EEM", "eem", "iShares Emerging Markets ETF", "markets", "equity"),
    ("EFA", "efa", "iShares EAFE ETF", "markets", "equity"),
    ("VWO", "vwo", "Vanguard Emerging Markets ETF", "markets", "equity"),
    ("TLT", "tlt", "iShares 20+ Year Treasury ETF", "markets", "rates"),
    ("SHY", "shy", "iShares 1-3 Year Treasury ETF", "markets", "rates"),
    ("IEF", "ief", "iShares 7-10 Year Treasury ETF", "markets", "rates"),
    ("LQD", "lqd", "iShares Investment Grade Bond ETF", "markets", "rates"),
    ("HYG", "hyg", "iShares High Yield Bond ETF", "markets", "rates"),
    ("ARKK", "arkk", "ARK Innovation ETF", "markets", "equity"),
    ("TAN", "tan", "Invesco Solar ETF", "markets", "equity"),
    ("HACK", "hack", "ETFMG Prime Cyber Security ETF", "markets", "equity"),
    ("BOTZ", "botz", "Global X Robotics & AI ETF", "markets", "equity"),
    ("URA", "ura", "Global X Uranium ETF", "markets", "commodity"),
]


def _make_yahoo_collector(
    ticker: str, name: str, display_name: str,
    domain: str, category: str,
) -> type[_YahooCollector]:
    class _Collector(_YahooCollector):
        _ticker = ticker
        meta = CollectorMeta(
            name=name,
            display_name=display_name,
            update_frequency="daily",
            api_docs_url=f"https://finance.yahoo.com/quote/{ticker}/",
            domain=domain,
            category=category,
            signal_type="ohlcv",
        )

    _Collector.__name__ = f"Yahoo_{name}"
    _Collector.__qualname__ = f"Yahoo_{name}"
    return _Collector


def get_yahoo_collectors() -> dict[str, type[_YahooCollector]]:
    return {t[1]: _make_yahoo_collector(*t) for t in YAHOO_TICKERS}
